# Auto-generated by create_mcp_server
# DATA_DIR: Safe directory for storing data files for this server
from pathlib import Path as _Path
# Use script's directory as DATA_DIR (works in both production and local dev)
DATA_DIR = _Path(__file__).parent

from fastmcp import FastMCP
import httpx

mcp = FastMCP("Cat Facts")

@mcp.tool()
async def get_cat_fact() -> dict:
    """Fetch a random cat fact from the Cat Fact API.
    
    Returns:
        dict: Contains 'fact' (the cat fact text) and 'length' (character count)
    """
    async with httpx.AsyncClient() as client:
        response = await client.get("https://catfact.ninja/fact")
        response.raise_for_status()
        return response.json()

if __name__ == "__main__":
    mcp.run()
