# Auto-generated by create_mcp_server
# DATA_DIR: Safe directory for storing data files for this server
from pathlib import Path as _Path
# Use script's directory as DATA_DIR (works in both production and local dev)
DATA_DIR = _Path(__file__).parent

from fastmcp import FastMCP
import os
import json
import boto3
from botocore.config import Config
from datetime import datetime, timedelta
import hashlib
import requests
from typing import Optional
import re
from bs4 import BeautifulSoup

mcp = FastMCP("Cloudflare R2 Image Hosting")

# Persistence
UPLOADS_FILE = DATA_DIR / "uploads.json"

def get_s3_client():
    """Create S3 client for R2."""
    return boto3.client(
        "s3",
        endpoint_url=os.environ.get("R2_ENDPOINT"),
        aws_access_key_id=os.environ.get("R2_ACCESS_KEY_ID"),
        aws_secret_access_key=os.environ.get("R2_SECRET_ACCESS_KEY"),
        config=Config(signature_version="s3v4"),
        region_name="auto"
    )

def load_uploads() -> list:
    """Load upload history."""
    if UPLOADS_FILE.exists():
        return json.loads(UPLOADS_FILE.read_text())
    return []

def save_uploads(uploads: list):
    """Save upload history."""
    UPLOADS_FILE.write_text(json.dumps(uploads, indent=2))

def download_image(url: str) -> tuple[bytes, str]:
    """
    Download image from URL.
    
    Returns:
        tuple of (image_bytes, content_type)
    """
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }
    
    response = requests.get(url, timeout=30, headers=headers)
    response.raise_for_status()
    
    content_type = response.headers.get("Content-Type", "").lower()
    
    # Detect from magic bytes if needed
    if not content_type or "image" not in content_type:
        magic = response.content[:8]
        if magic[:3] == b'\xff\xd8\xff':
            content_type = "image/jpeg"
        elif magic[:8] == b'\x89PNG\r\n\x1a\n':
            content_type = "image/png"
        elif magic[:6] in (b'GIF87a', b'GIF89a'):
            content_type = "image/gif"
        elif magic[:4] == b'RIFF' and response.content[8:12] == b'WEBP':
            content_type = "image/webp"
        else:
            raise ValueError("Could not detect image type")
    
    return response.content, content_type.split(";")[0].strip()

def get_extension(content_type: str) -> str:
    """Get file extension from content type."""
    return {
        "image/jpeg": "jpg",
        "image/png": "png",
        "image/gif": "gif",
        "image/webp": "webp"
    }.get(content_type, "jpg")


def extract_og_image(url: str) -> Optional[str]:
    """
    Extract og:image from a webpage.
    
    Args:
        url: The webpage URL
        
    Returns:
        The og:image URL or None if not found
    """
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }
    
    response = requests.get(url, timeout=30, headers=headers)
    response.raise_for_status()
    
    soup = BeautifulSoup(response.text, "html.parser")
    
    # Try og:image first
    og_image = soup.find("meta", property="og:image")
    if og_image and og_image.get("content"):
        return og_image["content"]
    
    # Try twitter:image as fallback
    twitter_image = soup.find("meta", attrs={"name": "twitter:image"})
    if twitter_image and twitter_image.get("content"):
        return twitter_image["content"]
    
    # Try twitter:image:src
    twitter_image_src = soup.find("meta", attrs={"name": "twitter:image:src"})
    if twitter_image_src and twitter_image_src.get("content"):
        return twitter_image_src["content"]
    
    return None


def extract_article_info(url: str) -> dict:
    """
    Extract article metadata from a webpage.
    
    Returns:
        dict with title, description, image_url
    """
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }
    
    response = requests.get(url, timeout=30, headers=headers)
    response.raise_for_status()
    
    soup = BeautifulSoup(response.text, "html.parser")
    
    result = {
        "title": None,
        "description": None,
        "image_url": None,
        "source_url": url
    }
    
    # Title
    og_title = soup.find("meta", property="og:title")
    if og_title and og_title.get("content"):
        result["title"] = og_title["content"]
    elif soup.title:
        result["title"] = soup.title.string
    
    # Description
    og_desc = soup.find("meta", property="og:description")
    if og_desc and og_desc.get("content"):
        result["description"] = og_desc["content"]
    else:
        meta_desc = soup.find("meta", attrs={"name": "description"})
        if meta_desc and meta_desc.get("content"):
            result["description"] = meta_desc["content"]
    
    # Image
    og_image = soup.find("meta", property="og:image")
    if og_image and og_image.get("content"):
        result["image_url"] = og_image["content"]
    else:
        twitter_image = soup.find("meta", attrs={"name": "twitter:image"})
        if twitter_image and twitter_image.get("content"):
            result["image_url"] = twitter_image["content"]
    
    return result


@mcp.tool()
def upload_image_from_url(
    image_url: str,
    folder: str = "uploads",
    custom_filename: Optional[str] = None
) -> str:
    """
    Download an image and upload it to R2.
    
    Args:
        image_url: URL of the image to upload
        folder: Folder/prefix in R2 bucket (default: "uploads")
        custom_filename: Optional custom filename (without extension)
    
    Returns:
        Public URL of the uploaded image
    """
    bucket = os.environ.get("R2_BUCKET_NAME")
    public_domain = os.environ.get("R2_PUBLIC_DOMAIN")
    
    if not bucket or not public_domain:
        return "❌ R2 not configured. Set R2_BUCKET_NAME and R2_PUBLIC_DOMAIN."
    
    # Download
    try:
        image_bytes, content_type = download_image(image_url)
    except Exception as e:
        return f"❌ Failed to download image: {str(e)}"
    
    # Generate filename
    ext = get_extension(content_type)
    if custom_filename:
        filename = f"{custom_filename}.{ext}"
    else:
        # Hash-based filename for deduplication
        hash_prefix = hashlib.md5(image_bytes).hexdigest()[:12]
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        filename = f"{timestamp}-{hash_prefix}.{ext}"
    
    key = f"{folder}/{filename}"
    
    # Upload to R2
    try:
        s3 = get_s3_client()
        s3.put_object(
            Bucket=bucket,
            Key=key,
            Body=image_bytes,
            ContentType=content_type
        )
    except Exception as e:
        return f"❌ Failed to upload to R2: {str(e)}"
    
    # Build public URL
    public_url = f"https://{public_domain}/{key}"
    
    # Save to history
    uploads = load_uploads()
    uploads.append({
        "key": key,
        "public_url": public_url,
        "source_url": image_url,
        "content_type": content_type,
        "size_bytes": len(image_bytes),
        "uploaded_at": datetime.now().isoformat()
    })
    save_uploads(uploads)
    
    return f"✅ Uploaded!\n\n**Public URL:** {public_url}\n**Size:** {len(image_bytes) / 1024:.1f} KB"


@mcp.tool()
def upload_from_article(
    article_url: str,
    folder: str = "articles"
) -> str:
    """
    Extract the featured image from a news article and upload it to R2.
    
    This fetches the article, extracts the og:image meta tag, downloads the image,
    and uploads it to R2 for public hosting.
    
    Args:
        article_url: URL of the news article
        folder: Folder/prefix in R2 bucket (default: "articles")
    
    Returns:
        Public URL of the uploaded image + article metadata
    """
    bucket = os.environ.get("R2_BUCKET_NAME")
    public_domain = os.environ.get("R2_PUBLIC_DOMAIN")
    
    if not bucket or not public_domain:
        return "❌ R2 not configured. Set R2_BUCKET_NAME and R2_PUBLIC_DOMAIN."
    
    # Extract article info
    try:
        article_info = extract_article_info(article_url)
    except Exception as e:
        return f"❌ Failed to fetch article: {str(e)}"
    
    if not article_info["image_url"]:
        return f"❌ No og:image found in article.\n\nTitle: {article_info.get('title', 'Unknown')}"
    
    # Download the image
    try:
        image_bytes, content_type = download_image(article_info["image_url"])
    except Exception as e:
        return f"❌ Failed to download image from {article_info['image_url']}: {str(e)}"
    
    # Generate filename
    ext = get_extension(content_type)
    hash_prefix = hashlib.md5(image_bytes).hexdigest()[:12]
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    filename = f"{timestamp}-{hash_prefix}.{ext}"
    key = f"{folder}/{filename}"
    
    # Upload to R2
    try:
        s3 = get_s3_client()
        s3.put_object(
            Bucket=bucket,
            Key=key,
            Body=image_bytes,
            ContentType=content_type
        )
    except Exception as e:
        return f"❌ Failed to upload to R2: {str(e)}"
    
    # Build public URL
    public_url = f"https://{public_domain}/{key}"
    
    # Save to history
    uploads = load_uploads()
    uploads.append({
        "key": key,
        "public_url": public_url,
        "source_url": article_info["image_url"],
        "article_url": article_url,
        "article_title": article_info.get("title"),
        "content_type": content_type,
        "size_bytes": len(image_bytes),
        "uploaded_at": datetime.now().isoformat()
    })
    save_uploads(uploads)
    
    result = f"✅ Uploaded!\n\n"
    result += f"**Public URL:** {public_url}\n"
    result += f"**Size:** {len(image_bytes) / 1024:.1f} KB\n\n"
    result += f"**Article:** {article_info.get('title', 'Unknown')}\n"
    if article_info.get('description'):
        result += f"**Description:** {article_info['description'][:200]}...\n"
    
    return result


@mcp.tool()
def get_article_info(article_url: str) -> str:
    """
    Extract metadata from a news article without uploading anything.
    
    Useful for previewing what will be extracted before uploading.
    
    Args:
        article_url: URL of the news article
    
    Returns:
        Article title, description, and image URL
    """
    try:
        info = extract_article_info(article_url)
    except Exception as e:
        return f"❌ Failed to fetch article: {str(e)}"
    
    result = "📰 Article Info:\n\n"
    result += f"**Title:** {info.get('title', 'Not found')}\n"
    result += f"**Description:** {info.get('description', 'Not found')}\n"
    result += f"**Image URL:** {info.get('image_url', 'Not found')}\n"
    
    return result


@mcp.tool()
def upload_image_bytes(
    image_base64: str,
    filename: str,
    content_type: str = "image/jpeg",
    folder: str = "uploads"
) -> str:
    """
    Upload base64-encoded image to R2.
    
    Args:
        image_base64: Base64-encoded image data
        filename: Filename including extension
        content_type: MIME type (default: image/jpeg)
        folder: Folder/prefix in R2 bucket
    
    Returns:
        Public URL of the uploaded image
    """
    import base64
    
    bucket = os.environ.get("R2_BUCKET_NAME")
    public_domain = os.environ.get("R2_PUBLIC_DOMAIN")
    
    if not bucket or not public_domain:
        return "❌ R2 not configured. Set R2_BUCKET_NAME and R2_PUBLIC_DOMAIN."
    
    try:
        image_bytes = base64.b64decode(image_base64)
    except Exception as e:
        return f"❌ Invalid base64 data: {str(e)}"
    
    key = f"{folder}/{filename}"
    
    try:
        s3 = get_s3_client()
        s3.put_object(
            Bucket=bucket,
            Key=key,
            Body=image_bytes,
            ContentType=content_type
        )
    except Exception as e:
        return f"❌ Failed to upload to R2: {str(e)}"
    
    public_url = f"https://{public_domain}/{key}"
    
    # Save to history
    uploads = load_uploads()
    uploads.append({
        "key": key,
        "public_url": public_url,
        "source_url": None,
        "content_type": content_type,
        "size_bytes": len(image_bytes),
        "uploaded_at": datetime.now().isoformat()
    })
    save_uploads(uploads)
    
    return f"✅ Uploaded!\n\n**Public URL:** {public_url}\n**Size:** {len(image_bytes) / 1024:.1f} KB"


@mcp.tool()
def delete_image(key: str) -> str:
    """
    Delete an image from R2.
    
    Args:
        key: The full key/path of the image (e.g., "uploads/image.jpg")
    """
    bucket = os.environ.get("R2_BUCKET_NAME")
    
    if not bucket:
        return "❌ R2 not configured."
    
    try:
        s3 = get_s3_client()
        s3.delete_object(Bucket=bucket, Key=key)
    except Exception as e:
        return f"❌ Failed to delete: {str(e)}"
    
    # Remove from history
    uploads = load_uploads()
    uploads = [u for u in uploads if u["key"] != key]
    save_uploads(uploads)
    
    return f"✅ Deleted: {key}"


@mcp.tool()
def list_uploads(limit: int = 20, folder: Optional[str] = None) -> str:
    """
    List recent uploads from history.
    
    Args:
        limit: Maximum number to return
        folder: Optional - filter by folder prefix
    """
    uploads = load_uploads()
    
    if folder:
        uploads = [u for u in uploads if u["key"].startswith(folder)]
    
    uploads.sort(key=lambda x: x["uploaded_at"], reverse=True)
    uploads = uploads[:limit]
    
    if not uploads:
        return "No uploads found."
    
    result = f"📁 Recent Uploads ({len(uploads)}):\n\n"
    for u in uploads:
        size_kb = u.get("size_bytes", 0) / 1024
        result += f"• **{u['key']}**\n"
        result += f"  {u['public_url']}\n"
        result += f"  {size_kb:.1f} KB | {u['uploaded_at'][:16]}\n"
        if u.get("article_title"):
            result += f"  📰 {u['article_title'][:50]}...\n"
        result += "\n"
    
    return result


@mcp.tool()
def cleanup_old_uploads(days_old: int = 7, folder: str = "instagram") -> str:
    """
    Delete uploads older than specified days.
    
    Args:
        days_old: Delete files older than this (default: 7)
        folder: Only clean this folder (default: "instagram")
    """
    bucket = os.environ.get("R2_BUCKET_NAME")
    if not bucket:
        return "❌ R2 not configured."
    
    cutoff = datetime.now() - timedelta(days=days_old)
    uploads = load_uploads()
    
    to_delete = [
        u for u in uploads
        if u["key"].startswith(folder)
        and datetime.fromisoformat(u["uploaded_at"]) < cutoff
    ]
    
    if not to_delete:
        return f"No uploads older than {days_old} days in '{folder}/'."
    
    s3 = get_s3_client()
    deleted = 0
    errors = 0
    
    for u in to_delete:
        try:
            s3.delete_object(Bucket=bucket, Key=u["key"])
            deleted += 1
        except Exception:
            errors += 1
    
    # Update history
    save_uploads([u for u in uploads if u not in to_delete])
    
    return f"✅ Cleaned up {deleted} files ({errors} errors)"


if __name__ == "__main__":
    mcp.run()
